# Generated by Django 5.0.3 on 2024-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], max_length=10),
        ),
    ]
